Online_Judge/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlineJudge/',include('onlineJudge.urls')),
]

onlineJudge/urls.py
from django.urls import path
from . import views

app_name = 'onlineJudge'
urlpatterns = [
    path('register/', views.register_request, name="register"),
    path('login/', views.login_request, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('login/check/', views.login_check, name="login_check"),
    path('register/verify/', views.register_verify, name="register_verify"),

    path('', views.login_request, name="login"),
    path('problems/',views.problems, name='problems'),
    path('problem/<int:problem_id>/',views.problemDetails,name='problem_detail'),
    path('submit/<int:problem_id>/',views.problemSubmit,name="submit"),
    path('submit/<str:status>/', views.result,name="result"),
    path('problem/',views.problemSubmissions,name='submissions'),
]

onlineJudge/models.py
from sqlite3 import Timestamp
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User


class Problems(models.Model):
    Problem_Name = models.CharField(max_length=50)
    Problem_Description = models.TextField()
    difficulty_choice=(
        ('easy','easy'),
        ('medium','medium'),
        ('difficult','difficult'),
    )
    Problem_Difficulty = models.CharField(max_length=20,choices=difficulty_choice,default='easy')
    def __str__(self):
        return self.Problem_Name

class Test_Case(models.Model):
    Pname = models.ForeignKey(Problems, on_delete=models.CASCADE)
    test_input = models.FileField(upload_to='onlineJudge/test_input/',null=False)
    test_output = models.FileField(upload_to='onlineJudge/test_output/',null=False)


class Solutions(models.Model):
    user =models.ForeignKey(User,on_delete=models.CASCADE,)
    Pname = models.ForeignKey(Problems,on_delete=models.CASCADE)
    language_choices=(
        ('c++','cpp'),
    )
    Language = models.CharField(max_length=20,choices=language_choices)
    Code_file = models.FileField(upload_to='onlineJudge/Code_file', null=False)
    verdict_choice=(
        ('PR','Processing'),
        ('WA','Wrong Answer'),
        ('AC','All Correct'),
    )
    verdict = models.CharField(max_length=10,choices=verdict_choice)
    timestamp= models.TimeField(auto_now_add=True)

onlineJudge/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

onlineJudge/views.py
import filecmp,subprocess
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.base import File
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from onlineJudge.models import Problems,Solutions,Test_Case

# Create your views here.
def register_request(request):
    return render(request , 'onlineJudge/register.html')

def register_verify(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            username = request.POST['username']
            password = request.POST['password1']
            email = request.POST['email']

            new_user = User.objects.create_user(username,email, password)
            new_user.save()
            messages.success(request , "Registration Successful", extra_tags='alert alert-success')
            return HttpResponseRedirect('/onlineJudge/problems/')
        else:
            messages.succes(request , "Both passsword should be same.", extra_tags='alert alert-danger')
            return HttpResponseRedirect('/onlineJudge/register/')
    else:
        return HttpResponse("Usage: Post method is not used.")

def login_request(request):
    return render(request ,'onlineJudge/login.html')

def login_check(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request , "Logged in successfully.", extra_tags='alert alert-success')
            return HttpResponseRedirect('/onlineJudge/problems/')
        else:
            messages.success(request , "Log in failed!! check username or password.", extra_tags='alert alert-danger')
            return HttpResponseRedirect('/onlineJudge/login/')
    else:
        return HttpResponse("Usage: Method used is not POST.")

def log_out(request):
    logout(request)
    messages.success(request , "Logout succesfully.", extra_tags='alert alert-success')
    return HttpResponseRedirect('/onlineJudge')

@login_required(login_url="/onlineJudge/login/")
def problems(request):
    problems_list = Problems.objects.all()
    context = {'problems_list' : problems_list}
    return render(request,'onlineJudge/problems.html',context)

@login_required(login_url="/onlineJudge/login/")
def problemDetails(request,problem_id,msg=""):
    problem = get_object_or_404(Problems,pk=problem_id)
    context = {
        'problem':problem,
        'message':msg
    }
    return render(request,'onlineJudge/problemStatement.html',context)

@login_required(login_url="/onlineJudge/login/")
def problemSubmit(request,problem_id):
    problem=Problems.objects.get(pk=problem_id)
    test=Test_Case.objects.get(Pname__Problem_Name=problem.Problem_Name)

    if request.method == "POST":
        
        userfile=request.FILES.get('solution',False)
        codeEditor=request.POST.get('solutionText',False)
        if(userfile):
            code=userfile.read()
            with open('temp.cpp','wb+') as tempf:
                tempf.write(code)
            tempf.close()

            outputf=open('tempf_out.txt','w')
            testout=(test.test_output.url)[1:]
            subprocess.call(["g++","temp.cpp","-o","temp.exe"],shell=True)
            k=subprocess.call(['temp.exe'],stdin=test.test_input,stdout=outputf,shell=True)
            outputf.close()
            if k:
                return HttpResponse("Internal error occurs")
            else:
                result=filecmp.cmp('tempf_out.txt',testout,shallow=False)
                if result:
                    file=open('temp.cpp')
                    myfile=File(file)
                    sol=Solutions(
                        user=request.user,
                        Pname=problem,
                        Language=request.POST['language'],
                        Code_file=myfile,
                        verdict='AC'
                    )
                    sol.save()
                    file.close()
                    return HttpResponseRedirect("/onlineJudge/submit/correct_ans/")
                else:
                    file =  open('temp.cpp')
                    myfile = File(file)
                    sol = Solutions(
                        user=request.user,
                        Pname=problem,
                        Language=request.POST['language'],
                        Code_file=myfile,
                        verdict='WA'
                    )
                    sol.save()
                    file.close()
                    return HttpResponseRedirect("/onlineJudge/submit/wrong_ans/")

        elif(codeEditor):
            byteContent=codeEditor.encode()
            with open('temp.cpp','wb+') as tempf:
                tempf.write(byteContent)
            tempf.close()

            outputf=open('tempf_out.txt','w')
            testint=test.test_input
            testout=(test.test_output.url)[1:]
            subprocess.call(["g++","temp.cpp","-o","temp.exe"],shell=True)
            k=subprocess.call(['temp.exe'],stdin=testint,stdout=outputf,shell=True)
            
            outputf.close()
            if k:
                return HttpResponse("Internal error occurs")
            else:
                result=filecmp.cmp('tempf_out.txt',testout,shallow=False)
                if result:
                    file=open('temp.cpp')
                    myfile=File(file)
                    sol=Solutions(
                        user=request.user,
                        Pname=problem,
                        Language=request.POST['language'],
                        Code_file=myfile,
                        verdict='AC'
                    )
                    sol.save()
                    file.close()
                    return HttpResponseRedirect("/onlineJudge/submit/correct_ans/")
                else:
                    file =  open('temp.cpp')
                    myfile = File(file)
                    sol = Solutions(
                        user=request.user,
                        Pname=problem,
                        Language=request.POST['language'],
                        Code_file=myfile,
                        verdict='WA'
                    )
                    sol.save()
                    file.close()
                    return HttpResponseRedirect("/onlineJudge/submit/wrong_ans/")
        else: 
            message="Please select a code file!!!!!"
            return problemDetails(request,problem_id,message)

    else:
        return HttpResponse("Method is not POST")

@login_required(login_url="/onlineJudge/login/")
def result(request , status):
    context = {'status':status}
    return render(request,'onlineJudge/submit.html',context)

@login_required(login_url="/onlineJudge/login/")
def problemSubmissions(request):
    submissions = Solutions.objects.all().order_by('-id')[:10]
    return render(request,'onlineJudge/submission.html', {'submissions' : submissions})

onlineJudge/templates/onlineJudge/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
		integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: rgb(235, 227, 183) !important;
		}

		.user_card {
			margin-top: auto;
			margin-bottom: auto;
			background: #a7e2ee !important;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}
		input{
			font-family: Arial, Helvetica, sans-serif;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div>

			</div>
			<div class=" col-5 user_card">
				<div class="d-flex justify-content-center">
					<h2 class="text-white">LOGIN</h2>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form action="{% url 'onlineJudge:login_check' %}" method="post">
						{% csrf_token %}

						<h5 class="fw-normal mb-4 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

						<div class="form-outline mb-4 d-flex flex-row align-items-center">
							<i class="fas fa-at fa-lg me-3 fa-fw"></i>
							<input type="text" name="username" id="form2Example17" class="form-control form-control-lg"
								placeholder="Username" required="required" />
						</div>
						<div class="form-outline mb-4 d-flex flex-row align-items-center">
							<i class="fas fa-key fa-lg me-3 fa-fw"></i>
							<input type="password" id="form2Example27" name="password"
								class="form-control form-control-lg" placeholder="Password" required="required" />
						</div>
						<div class="pt-1 mb-4 mx-4">
							<button class="btn btn-primary btn-lg btn-block  mx-3" type="submit">Login</button>
							<a class="small text-muted mx-3" href="#!">Forgot password?</a>
						</div>

						<p class="mb-4 pb-lg-2" style="color: #393f81;">Don't have an account? <a
								href="{% url 'onlineJudge:register' %}" style="color: #2575ff;">Sign Up</a></p>

						{% if messages %}
						{% for message in messages %}
						<div class="{{ message.tags }} alert-dismissible fade show" role="alert">
							{{ message }}
							<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
						{% endfor %}
						{% endif %}

						<a href="#!" class="small text-muted">Terms of use.</a>
						<a href="#!" class="small text-muted">Privacy policy</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

onlineJudge/templates/onlineJudge/problemStatement.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <h1 align="center">{{ problem.Problem_Name }}</h1>
    <p> {{ problem.Problem_Description }}</p>
    <form action="{% url 'onlineJudge:submit' problem.id %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="language">language:</label>
            <select name="language" id="language" required="required">
                <option value="">choose language</option>
                <option value="c++">C++</option>
            </select><br><br>
            <div align="center">
                <label for="solutionText">Write your code here:</label><br>
                <textarea id="solutionText" name="solutionText" rows="10" cols="100"></textarea>
                <br><br>
                <input type="file" id="solution" name="solution">
                <input type="submit" value="Submit">
                <h3>{{message}}</h3>
            </div>
        </fieldset>
       
    </form>
</body>
</html>

onlineJudge/templates/onlineJudge/problems.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <style>
    html,
    body,
    .tablestr {
      height: 100%;
    }

    .gradient {
      background: #6a11cb;
      background: -webkit-linear-gradient(to top, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1), rgb(106, 185, 231));
      background: linear-gradient(to top, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1), rgb(106, 185, 231))
    }

    table td,
    table th {
      text-overflow: ellipsis;
      white-space: nowrap;
      overflow: hidden;
    }

    thead th {
      color: rgb(245, 239, 239);
    }

    tbody td {
      font-weight: 500;
      color: rgba(28, 27, 27, 0.65);

    }
    
    #shadow {
      box-shadow: 0 2px 7px 0 rgba(0, 0, 0, .25), 0 3px 10px 3px rgba(0, 0, 0, 0.28) !important;
    }
  </style>
</head>

<body>
  <section class="tablestr">
    <div class="gradient h-100">
      <div class="p-5 text-center">
        <h1 class="mb-lg-5 text-dark rounded" style="background-color: rgb(135, 245, 245);">PROBLEMS</h1>
      </div>
      <div class="mask d-flex h-100">
        <div class="container" style="text-align: center;">
          <div id="shadow" class="table-responsive" data-mdb-perfect-scrollbar="true"
            style="position: relative; ">
            {% csrf_token %}
            {% if problems_list %}
            <div class="card">
              <table class="table table-light table-borderless table-hover mb-0 bg-white">
                <thead class="table-dark sticky-top">
                  <tr>
                    <th scope="col" style="width: 50%;">PROBLEM</th>
                    <th scope="col" style="width: 20%;">DIFFICULTY</th>
                  </tr>
                </thead>
                <tbody>
                  {% for problem in problems_list %}
                  <tr>
                    <td class="text-white"><a href="{% url 'onlineJudge:problem_detail' problem.id %}">{{ problem.Problem_Name }}</a></td>
                    <td>{{ problem.Problem_Difficulty }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% else %}
            <div class="card bg-white"><h4><b>Sorry,No Problems right now.</b></h4></div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>

onlineJudge/templates/onlineJudge/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}

		.user_card {
			padding-left: 10px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
			margin-left: 20px;
		}

		#form-title {
			color: #fff;
		}
		
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="{% url 'onlineJudge:register_verify' %}">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
								<div class="form-outline flex-fill mb-0">
									<input type="text" id="form3Example1c" class="form-control" name="username"
										placeholder="Username" required="required" />
								</div>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
								<div class="form-outline flex-fill mb-0">
									<input type="email" id="form3Example3c" class="form-control" name="email"
										placeholder="name@example.com" required="required" />
								</div>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
								<div class="form-outline flex-fill mb-0">
									<input type="password" id="form3Example4c" class="form-control" name="password1"
										placeholder="Password" required="required" />
								</div>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
								<div class="form-outline flex-fill mb-0">
									<input type="password" id="form3Example4cd" class="form-control" name="password2"
										placeholder="Re-enter Password" required="required" />
								</div>
							</div>
						</div>


						<div class="form-check d-flex mb-2">
							<input class="form-check-input me-2" type="checkbox" value="yes" id="form2Example3c" required="required" />
							<label class="form-check-label" for="form2Example3">I agree all statements in <a href="#!">Terms of service</a></label>
						</div>

						{% if messages %}
						{% for message in messages %}
						<div class="{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}
							<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
						{% endfor %}
						{% endif %}

						<div class="d-flex justify-content-center mx-3 mb-2 mb-lg-4">
							<button type="submit" class="btn btn-primary btn-lg">Register Account</button>
						</div>
					</form>
				</div>

			</div>
		</div>
	</div>
	
</body>

</html>

onlineJudge/templates/onlineJudge/submission.html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    <div class="container">
        <table class="table mt-3">
            <thead class="p-4">
                <tr class="bg-secondary">
                    <th scope="col">PROBLEM NAME</th>
                    <th scope="col">User</th>
                    <th scope="col">VERDICT</th>
                    <th scope="col">LANGUAGE</th>
                    <th scope="col">TIME</th>
                </tr>
            </thead>
            <tbody>
                {% for submission in submissions %}
                {% if submission.verdict == "AC" %}
                <tr style="background-color: #4ce366e0;">
                    <th scope="row" class="text-capitalize">{{submission.Pname}}</th>
                    <td class="text-capitalize">{{submission.user}}</td>
                    <td class="text-capitalize">{{submission.verdict}}</td>
                    <td class="text-capitalize">{{submission.Language}}</td>
                    <td class="text-capitalize">{{submission.timestamp}}</td>
                </tr>
                {% elif submission.verdict == "WA"%}
                <tr style="background-color: #ff8463;">
                    <th scope="row" class="text-capitalize">{{submission.Pname}}</th>
                    <td class="text-capitalize">{{submission.user}}</td>
                    <td class="text-capitalize">{{submission.verdict}}</td>
                    <td class="text-capitalize">{{submission.Language}}</td>
                    <td class="text-capitalize">{{submission.timestamp}}</td>
                </tr>
                {% endif %}

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

onlineJudge/templates/onlineJudge/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
    <style>
        .bg-light{background-color: rgb(193, 238, 238)!important;}
        .shadow-4-strong{box-shadow:0 2px 15px -3px rgba(0,0,0,.16),0 10px 20px -2px rgba(0,0,0,.1)!important}
    </style>
</head>
<body>
    <div class="d-flex justify-content-center">
        {% if status == 'wrong_ans' %}
        <div class="card m-5  bg-light p-3 shadow-4-strong" style="width: 26rem;">
            {% load static %}
            <img src="{% static 'img/failure.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body text-center border-top border-warning">
                <p class="card-text text-warning font-weight-bold">Every master was once a beginner.<br>It worth one more try...</p><br>
                <a href="{% url 'onlineJudge:problems' %}" class="card-link btn btn-info m-2">Problems</a>
                <a href="{% url 'onlineJudge:submissions' %}" class="card-link btn btn-info m-2">Submissions</a>
            </div>
        </div>
        {% elif status == 'correct_ans' %}
        <div class="card m-5  bg-light p-3 shadow-4-strong" style="width: 26rem;">
            {% load static %}
            <img src="{% static 'img/sucess.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body text-center border-top border-success">
                <p class="card-text text-success font-weight-bold">Great Work! Keep it up.<br>Great form let's face few more challenges</p><br>
                <a href="{% url 'onlineJudge:problems' %}" class="card-link btn btn-info m-2">Problems</a>
                <a href="{% url 'onlineJudge:submissions' %}" class="card-link btn btn-info m-2">Submissions</a>
            </div>
        </div>
        {% endif %}
    </div>
</body>
</html>